module com.example.antsimulator {
    requires javafx.controls;
    requires javafx.fxml;
    requires transitive javafx.graphics;

    requires com.dlsc.formsfx;
    requires java.sql;
    requires java.desktop;
    requires org.json;
    exports app;
    exports model.colony.tasks;
    exports model;
    opens model to javafx.fxml;
    exports view;
    opens view to javafx.fxml;
    exports controller;
    opens controller to javafx.fxml;
    exports model.entity.being.ants;
    opens model.entity.being.ants to javafx.fxml;
    exports model.colony;
    opens model.colony to javafx.fxml;
    exports model.colony.antnest;
    opens model.colony.antnest to javafx.fxml;
    exports model.colony.events;
    opens model.colony.events to javafx.fxml;
    exports model.entity.being.ants.behavior;
    opens model.entity.being.ants.behavior to javafx.fxml;
    exports model.world;
    opens model.world to javafx.fxml;
    exports model.entity.being.ants.state;
    opens model.entity.being.ants.state to javafx.fxml;
    exports model.entity.being.ants.movement;
    opens model.entity.being.ants.movement to javafx.fxml;
    exports model.entity.being.ants.status;
    opens model.entity.being.ants.status to javafx.fxml;
    exports model.datastructures;
    opens model.datastructures to javafx.fxml;
    exports controller.mouseTool;
    opens controller.mouseTool to javafx.fxml;
    exports view.sprite;
    opens view.sprite to javafx.fxml;
    exports model.entity.being.ants.creation;
    opens model.entity.being.ants.creation to javafx.fxml;
    exports model.entity;
    opens model.entity to javafx.fxml;
    exports model.entity.being;
    opens model.entity.being to javafx.fxml;
    exports model.entity.item;
    opens model.entity.item to javafx.fxml;
}